### ISSUE TITLE
Plugin not responding since today

### ISSUE THREAD

**Issue by cLnx-bruh** [digitalocean/terraform-provider-digitalocean#851] opened 2022-07-29 10:59 UTC
# Bug Report

Straight up doesnt work, unable to run plan/apply and seems to affect multiple versions in multiple environments so not local issue

## Describe the bug
Tried running terraform plan/apply for one of my projects and got bellow error:

Error: Plugin did not respond

  with module.KubernetesCluster.data.digitalocean_kubernetes_cluster.tf_cluster,
  on ../../Module/KubernetesCluster/resources.tf line 24, in data "digitalocean_kubernetes_cluster" "tf_cluster":
  24: data "digitalocean_kubernetes_cluster" "tf_cluster" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more
details.

Stack trace from the terraform-provider-digitalocean_v2.21.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xcecf67]

goroutine 67 [running]:
github.com/digitalocean/terraform-provider-digitalocean/digitalocean.flattenCredentials({0xc00096b830, 0x17}, {0xc0000a30b0, 0x4}, 0x0)
	github.com/digitalocean/terraform-provider-digitalocean/digitalocean/resource_digitalocean_kubernetes_cluster.go:640 +0x47
github.com/digitalocean/terraform-provider-digitalocean/digitalocean.digitaloceanKubernetesClusterRead(0xc000154a00, 0xc0006ab440, 0x24?)
	github.com/digitalocean/terraform-provider-digitalocean/digitalocean/resource_digitalocean_kubernetes_cluster.go:383 +0xb28
github.com/digitalocean/terraform-provider-digitalocean/digitalocean.dataSourceDigitalOceanKubernetesClusterRead({0x1[18](https://github.com/hooloovoodoo/vb-infra/runs/7577261962?check_suite_focus=true#step:6:19)bf10?, 0xc0006d5000?}, 0x7f0eca391108?, {0xdef300?, 0xc0006d60c0?})
	github.com/digitalocean/terraform-provider-digitalocean/digitalocean/datasource_digitalocean_kubernetes_cluster.go:154 +0x27e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00057c1c0, {0x118bf10, 0xc0006d5000}, 0xc0000b8f90?, {0xdef300, 0xc0006d60c0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:358 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc00057c1c0, {0x118bf10, 0xc0006d5000}, 0xc00008c900, {0xdef300, 0xc0006d60c0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:569 +0xf7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc00000c030, {0x118bf10, 0xc0006d5000}, 0xc00092f0a0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:1133 +0x339
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0001a1600, {0x118bfb8?, 0xc0006d9aa0?}, 0xc00091a8c0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:478 +0x31b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0xeba880?, 0xc0001a1600}, {0x118bfb8, 0xc0006d9aa0}, 0xc000774840, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00047b340, {0x118f330, 0xc000352a80}, 0xc0000a8300, 0xc00042a840, 0x176c3b0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1[19](https://github.com/hooloovoodoo/vb-infra/runs/7577261962?check_suite_focus=true#step:6:20)4 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc00047b340, {0x118f330, 0xc000352a80}, 0xc0000a8300, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x28a

Error: The terraform-provider-digitalocean_v2.[21](https://github.com/hooloovoodoo/vb-infra/runs/7577261962?check_suite_focus=true#step:6:22).0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

I run the command locally, its for my pet project, since though the issue is with my code i didn't want to troubleshoot it and switched to another project and got the same error when running from github actions, different repos, different code, no connection between the 2. everything worked fine last night and i made no changes since that.

Affected Resource(s)
By the looks of logs its seem Kubernetes cluster is affected

 "If this issue appears to affect multiple resources, it may be an issue with
Terraform's core, so please mention this. "

Expected Behavior
Terraform plan/apply wouldn't throw an error

Actual Behavior
Throws and error above

Steps to Reproduce
Run terraform apply with DO provider 2.19.0 to 2.22

**Expected behavior**
i run the 1.2.3 version and bumped up to 1.2.5 but it doesnt help

**Comment by baznikin** [comment] 2022-07-29 11:47
Same issue!

```
╷
│ Error: Plugin did not respond
│ 
│   with module.xxxx.digitalocean_kubernetes_cluster.cluster,
│   on ../../modules/xxxx-app/main.tf line 11, in resource "digitalocean_kubernetes_cluster" "cluster":
│   11: resource "digitalocean_kubernetes_cluster" "cluster" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.xxxx.digitalocean_loadbalancer.gateway,
│   on ../../modules/xxxx-app/main.tf line 272, in resource "digitalocean_loadbalancer" "gateway":
│  272: resource "digitalocean_loadbalancer" "gateway" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-digitalocean_v2.21.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xcecf67]

goroutine 70 [running]:
github.com/digitalocean/terraform-provider-digitalocean/digitalocean.flattenCredentials({0xc000a08948, 0x13}, {0xc0009c0788, 0x4}, 0x0)
	github.com/digitalocean/terraform-provider-digitalocean/digitalocean/resource_digitalocean_kubernetes_cluster.go:640 +0x47
github.com/digitalocean/terraform-provider-digitalocean/digitalocean.digitaloceanKubernetesClusterRead(0xc000378c80, 0xc0005f5b00, 0xc0000c2000?)
	github.com/digitalocean/terraform-provider-digitalocean/digitalocean/resource_digitalocean_kubernetes_cluster.go:383 +0xb28
github.com/digitalocean/terraform-provider-digitalocean/digitalocean.resourceDigitalOceanKubernetesClusterRead({0x118bf10?, 0xc000714180?}, 0xc000631600, {0xdef300?, 0xc000718480?})
	github.com/digitalocean/terraform-provider-digitalocean/digitalocean/resource_digitalocean_kubernetes_cluster.go:311 +0x1ea
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00021e460, {0x118bf10, 0xc000714180}, 0x24?, {0xdef300, 0xc000718480})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:358 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00021e460, {0x118bf10, 0xc000714180}, 0xc000615d40, {0xdef300, 0xc000718480})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0000aa090, {0x118bf10, 0xc000714180}, 0xc000714200)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x43f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00012d380, {0x118bfb8?, 0xc00064a1b0?}, 0xc000624ae0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x33c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xeba880?, 0xc00012d380}, {0x118bfb8, 0xc00064a1b0}, 0xc000624a80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003fec40, {0x118f330, 0xc00041c000}, 0xc0006cb700, 0xc0003aa810, 0x176c350, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc0003fec40, {0x118f330, 0xc00041c000}, 0xc0006cb700, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x28a

Error: The terraform-provider-digitalocean_v2.21.0 plugin crashed!
```

**Comment by miguel-castro-nearseatech** [comment] 2022-07-29 11:51
Seems to be specific for some types of resources/data sources. Our base infrastructure  works fine, but the app specific one does not.

We're using terraform cloud to run it, by the way.

I though this was a DO api problem, but I see nothing on https://status.digitalocean.com/

```
╷
│ Error: Plugin did not respond
│ 
│   with data.digitalocean_kubernetes_cluster.***,
│   on data.outputs.tf line 6, in data "digitalocean_kubernetes_cluster" "***":
│    6: data "digitalocean_kubernetes_cluster" "***" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain
│ more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with digitalocean_database_db.mysql,
│   on database.tf line 1, in resource "digitalocean_database_db" "mysql":
│    1: resource "digitalocean_database_db" "mysql" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with data.digitalocean_database_ca.mysqlCa,
│   on database.tf line 15, in data "digitalocean_database_ca" "mysqlCa":
│   15: data "digitalocean_database_ca" "mysqlCa" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain
│ more details.
╵

Stack trace from the terraform-provider-digitalocean_v2.21.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xcecf67]

goroutine 31 [running]:
github.com/digitalocean/terraform-provider-digitalocean/digitalocean.flattenCredentials({0xc0006c4348, 0x16}, {0xc000545578, 0x4}, 0x0)
        github.com/digitalocean/terraform-provider-digitalocean/digitalocean/resource_digitalocean_kubernetes_cluster.go:640 +0x47
github.com/digitalocean/terraform-provider-digitalocean/digitalocean.digitaloceanKubernetesClusterRead(0xc0003d6c80, 0xc00078b0e0, 0x24?)
        github.com/digitalocean/terraform-provider-digitalocean/digitalocean/resource_digitalocean_kubernetes_cluster.go:383 +0xb28
github.com/digitalocean/terraform-provider-digitalocean/digitalocean.dataSourceDigitalOceanKubernetesClusterRead({0x118bf10?, 0xc00032ae00?}, 0x7ff745fac3c8?, {0xdef300?, 0xc0007554a0?})
        github.com/digitalocean/terraform-provider-digitalocean/digitalocean/datasource_digitalocean_kubernetes_cluster.go:154 +0x27e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0000141c0, {0x118bf10, 0xc00032ae00}, 0xc000861080?, {0xdef300, 0xc0007554a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:358 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0000141c0, {0x118bf10, 0xc00032ae00}, 0xc000960200, {0xdef300, 0xc0007554a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:569 +0xf7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000504030, {0x118bf10, 0xc00032ae00}, 0xc000872000)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:1133 +0x339
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc000522d00, {0x118bfb8?, 0xc0006b6780?}, 0xc0006ba140)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:478 +0x31b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0xeba880?, 0xc000522d00}, {0x118bfb8, 0xc0006b6780}, 0xc000500b40, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00017a540, {0x118f330, 0xc000490000}, 0xc0006c2100, 0xc000406840, 0x176c3b0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc00017a540, {0x118f330, 0xc000490000}, 0xc0006c2100, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x28a

Error: The terraform-provider-digitalocean_v2.21.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Operation failed: failed running terraform plan (exit 1)
```

**Comment by baznikin** [comment] 2022-07-29 11:53
Trace from my second cluster:

```
╷
│ Error: Plugin did not respond
│ 
│   with digitalocean_kubernetes_cluster.cluster,
│   on main.tf line 11, in resource "digitalocean_kubernetes_cluster" "cluster":
│   11: resource "digitalocean_kubernetes_cluster" "cluster" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-digitalocean_v2.21.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xcecf67]

goroutine 42 [running]:
github.com/digitalocean/terraform-provider-digitalocean/digitalocean.flattenCredentials({0xc000a12b20, 0xa}, {0xc000a12b08, 0x4}, 0x0)
	github.com/digitalocean/terraform-provider-digitalocean/digitalocean/resource_digitalocean_kubernetes_cluster.go:640 +0x47
github.com/digitalocean/terraform-provider-digitalocean/digitalocean.digitaloceanKubernetesClusterRead(0xc0004ca500, 0xc0009f4d80, 0xc00003c0b0?)
	github.com/digitalocean/terraform-provider-digitalocean/digitalocean/resource_digitalocean_kubernetes_cluster.go:383 +0xb28
github.com/digitalocean/terraform-provider-digitalocean/digitalocean.resourceDigitalOceanKubernetesClusterRead({0x118bf10?, 0xc000aea800?}, 0xc000a3f300, {0xdef300?, 0xc0005cd170?})
	github.com/digitalocean/terraform-provider-digitalocean/digitalocean/resource_digitalocean_kubernetes_cluster.go:311 +0x1ea
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00021a460, {0x118bf10, 0xc000aea800}, 0x24?, {0xdef300, 0xc0005cd170})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:358 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00021a460, {0x118bf10, 0xc000aea800}, 0xc000660750, {0xdef300, 0xc0005cd170})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0000b0000, {0x118bf10, 0xc000aea800}, 0xc000aea880)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x43f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0000b2d80, {0x118bfb8?, 0xc000af0c30?}, 0xc00068a060)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x33c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xeba880?, 0xc0000b2d80}, {0x118bfb8, 0xc000af0c30}, 0xc00068a000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00044d180, {0x118f330, 0xc000326a80}, 0xc0009d0600, 0xc0003fa690, 0x176c350, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc00044d180, {0x118f330, 0xc000326a80}, 0xc0009d0600, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x28a

Error: The terraform-provider-digitalocean_v2.21.0 plugin crashed!
```

**Comment by dangerbat** [comment] 2022-07-29 12:30
we are having the same issue since today but I did not see any commit from today :/
```
Stack trace from the terraform-provider-digitalocean_v2.21.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xcecf67]

...

Error: The terraform-provider-digitalocean_v2.21.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

**Comment by baznikin** [comment] 2022-07-29 12:46
Obviously, something changed from DigitalOcean API side

**Comment by dikirahman** [comment] 2022-07-29 13:18
i also got the same problem
```
Error: Plugin did not respond
│
│   with data.digitalocean_kubernetes_cluster.example,
│   on provider.tf line 28, in data "digitalocean_kubernetes_cluster" "example":
│   28: data "digitalocean_kubernetes_cluster" "example" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵
....................
Error: The terraform-provider-digitalocean_v2.18.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by dangerbat** [comment] 2022-07-29 13:37
I tried to proxy the requests that terraform is making. Here is where I think it stopped (seems logic based on the line number from the [error](https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/digitalocean/resource_digitalocean_kubernetes_cluster.go#L640) trace as well ): 
request: 
```
GET /v2/kubernetes/clusters/<clusterID>/credentials HTTP/2
Host: api.digitalocean.com
Accept: application/json
User-Agent: Terraform/1.1.8 godo/1.81.0
Authorization: Bearer <token>
Accept-Encoding: gzip, deflate
```
response:
```
HTTP/2 503 Service Unavailable
Date: Fri, 29 Jul 2022 13:27:28 GMT
Content-Type: application/json
Content-Length: 98
X-Gateway: Edge-Gateway
X-Response-From: service-error
Cf-Cache-Status: DYNAMIC
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare

{"id":"service_unavailable","message":"Failed to forward the request you made, please try again."}
```

**Comment by nalanj** [comment] 2022-07-29 14:09
I just had one run succeed. Not sure if that was just a blip or if it's fixed.

**Comment by VladyslavVolkov** [comment] 2022-07-29 14:09
Had same issue, but seems like resolved. At least no panic crash

**Comment by andrewsomething** [comment] 2022-07-29 14:19
There was indeed an issue with the DOKS API. Following up internally, a fix has been deployed and the cluster credentials endpoint should now be working as expected.

**Comment by nalanj** [comment] 2022-07-29 14:23
@andrewsomething not sure if it's known or not but I'm also getting a 404 on the https://api.digitalocean.com/v2/databases/[id]/dbs/[name] resource despite the name being listed when I list the databases. That's showing up as TF wanting to create new databases for me.

**Comment by miguel-castro-nearseatech** [comment] 2022-07-29 14:25
I also have the same issue as @nalanj , and doing apply fails because the DB is already there.

```
Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # digitalocean_database_db.mysql has been deleted
  - resource "digitalocean_database_db" "mysql" {
      - cluster_id = (sensitive) -> null
      - id         = ***/database/***" -> null
      - name       = "***" -> null
    }
```

**Comment by andrewsomething** [comment] 2022-07-29 14:33
@nalanj Thanks for flagging that. I can reproduce and am escalating internally.

**Comment by nalanj** [comment] 2022-07-29 14:34
@andrewsomething absolutely! Thanks for digging in and getting back to us here.

**Comment by dangerbat** [comment] 2022-07-29 15:04
@nalanj same here. I am getting 404 from the databases API.

**Comment by cLnx-bruh** [comment] 2022-07-29 15:33
Can confirm the database issue as well. Thanks for quick response @andrewsomething

**Comment by andrewsomething** [comment] 2022-07-29 16:31
The database issue should now be resolved as well. Thanks for baring with us through that bumpy ride today. 

I'm going to go ahead and close this issue, but feel free to reopen if you're still seeing problems

**Closed by andrewsomething** 2022-07-29 16:31 UTC
Labels: bug

**Comment by miguel-castro-nearseatech** [comment] 2022-07-29 16:35
Seems to be back to normal, thank you. :smile:

**Comment by miguel-castro-nearseatech** [comment] 2022-07-29 17:20
Just in case someone has the same issue:

An apply was triggered during the issue and the DB was removed from the state. I got to re-import it again:
```
terraform -chdir=terraform import -ignore-remote-version digitalocean_database_db.mysql id,name
```

**Comment by cLnx-bruh** [comment] 2022-07-29 22:24
@miguel-castro-nearseatech actually the same thing happened to me, i tried to import it but couldn't get the id of the database out, how do you do that? im using postgre btw

**Comment by miguel-castro-nearseatech** [comment] 2022-08-01 10:59
@cLnx-bruh Sorry, missed this, when you run the plan and it says it was deleted, you can see the id+name there:
```
Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # digitalocean_database_db.mysql has been deleted
  - resource "digitalocean_database_db" "mysql" {
      - cluster_id = (sensitive) -> null
      - id         = ***/database/***" -> null
      - name       = "***" -> null
    }
```
The "id" there will be `{id}/database/{name}`. I picked those up from there.

**Comment by iamkhalidbashir** [comment] 2022-08-11 12:40
Same issue on  my end
