### ISSUE TITLE
 "Kubernetes Metrics Server"

### ISSUE THREAD

**Issue by ibadullaev-inc4** [digitalocean/terraform-provider-digitalocean#914] opened 2022-12-26 22:03 UTC
Hi is it possible to install "Kubernetes Metrics Server" on my exsisting cluster, using terraform provider ? 

![image](https://user-images.githubusercontent.com/101882172/209585657-236d1235-719a-44b5-929b-db9d5374e228.png)

**Comment by andrewsomething** [comment] 2023-01-03 21:43
Hi @ibadullaev-inc4,

 This is a duplicate of https://github.com/digitalocean/terraform-provider-digitalocean/issues/575

Unfortunately Kubernetes 1-Click apps can be added to a cluster via the API, but it is not currently possible to remove them or list the ones that have been installed already via the API. So the feature does not fit very well with Terraform's state management as it is currently implemented.

**Closed by andrewsomething** 2023-01-03 21:43 UTC
Labels: enhancement
